### PR TITLE
Update the runtime

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by Eonfge** [comment]
Ow, I wonder if it all works in one go... this package is quite an oddity

**Comment by AsciiWolf** [comment]
I am sadly on a work computer here. @Eonfge Can you test the new build? Thanks!

**Comment by Eonfge** [comment]
> I am sadly on a work computer here. @Eonfge Can you test the new build? Thanks!

That doesn't stop me! Then again, I also maintain a few applications that my office uses professionally.

But I did spot something odd... it seems that SDL-compat is not working properly, or that it's build against the bundled version of SDL 2. How I think so? I got client-side decorations all the sudden;

Screenshot from 2023-10-23 13-57-50

Can you remove the `sdl2-no-libdecor` package? I don't think we need it anymore

**Comment by AsciiWolf** [comment]
I did some brief testing and it looks like that the same problem happens even with the sdl2-no-libdecor module removed. However, I would keep the module removed since it should not be needed for 23.08 if I am not mistaken.

**Comment by Eonfge** [comment]
Did another check... and it did properly build against the shared-modules version of SDL 2 so at least that's not a bug.

I remember that in the past, Zandronum would crash with libdecor. Now that it seems to work well, I think it's best to run the application using the runtime SDL version.

I'll give it another test when I'm at home, using some different hardware. If that all works, we got ourselves a good release :D

**Comment by AsciiWolf** [comment]
Yup. And the client-side window decoration issue seems to be a small problem that can be fixed later if needed. Everything else that I tested did work fine. :-)

**Pull request merged**
