### PR TITLE
Update the runtime

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Doomseeker works fine, but Zandronum crashes on:

`/app/bin/zandronum: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory`

**Comment by AsciiWolf** [comment]
```
[📦 com.zandronum.Zandronum ~]$ ls -la /usr/lib/x86_64-linux-gnu/|grep libcrypto
-rwxr-xr-x. 4 nfsnobody nfsnobody  4670056  5. zář 18.52 libcrypto.so.3
```

The `libcrypto.so.1.1` sadly seems to be missing in the 22.08 runtime.

**Comment by Eonfge** [comment]
mmh. Feel free to add it, got to find a way to get it working. Zandronum is a bit all-over-the-place with technology, so I don't mind adding some extra dependencies

**Comment by AsciiWolf** [comment]
I have looked into the issue, but building openssl1.1 seems like an overkill. On regular distros, there is a libssl1.1/openssl1.1 compat package and libssl.so.1.1 was also present on 21.08 runtime, but it is not the case with 22.08 fd runtime. This seems more like a regression to me, so it would be better to report the issue [here](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues). I will do it when I have more time.

Here is a comparison between fd 21.08 and fd 22.08 runtimes:

```
# 21.08
$ ls -l /usr/lib/x86_64-linux-gnu/|grep libssl
-rwxr-xr-x.  6 nfsnobody nfsnobody   621440  5. srp 22.58 libssl.so.1.1
-rw-r--r--.  6 nfsnobody nfsnobody   430120  3. kvě 12.29 libssl3.so

# 22.08
$ ls -l /usr/lib/x86_64-linux-gnu/|grep libssl
-rwxr-xr-x. 4 nfsnobody nfsnobody   698128  5. zář 18.52 libssl.so.3
-rw-r--r--. 4 nfsnobody nfsnobody   430160  5. zář 18.52 libssl3.so
```

**Comment by AsciiWolf** [comment]
Oops, I forgot that it is actually libcrypto that is used by Zandronum, not the main libssl lib, sorry. Here is the right comparison:
```

# 21.08
$ ls -l /usr/lib/x86_64-linux-gnu/|grep libcrypto
-rwxr-xr-x.  6 nfsnobody nfsnobody  3083744  5. srp 22.58 libcrypto.so.1.1

# 22.08
$ ls -l /usr/lib/x86_64-linux-gnu/|grep libcrypto
-rwxr-xr-x. 4 nfsnobody nfsnobody  4670056  5. zář 18.52 libcrypto.so.3
```

So, the problem is that there is only `libssl.so.3` / `libcrypto.so.3` on 22.08 fd runtime without compat `libssl.so.1.1` / `libcrypto.so.1.1` libs.

**Comment by Eonfge** [comment]
Wait, so the SDL-compat update fixed the ssl issue?

**Comment by AsciiWolf** [comment]
It did not, sadly. I am going to report it as an upstream (Freedesktop SDK) issue.

**Comment by AsciiWolf** [comment]
@Eonfge It seems to work fine now. :-)

**Comment by Eonfge** [comment]
Great work! Thanks for helping a bit with this one since I only had so much time.

**Pull request merged**
